server:
  port: 8090

spring:
  application:
    name: home360-microservice-home
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
